jelu:
  database:
    path: ${user.home}/.jelu/database/
  files:
    images: '${user.home}/.jelu/files/images/'
    imports: '${user.home}/.jelu/files/imports/'
  session:
    duration: 604800 #7 days
  metadataProviders:
    - is-enabled: false
      apiKey: ""
      order: -100000
      name: "jelu-debug"
  metadata:
    calibre:
      path: /usr/bin/fetch-ebook-metadata
#  cors.allowed-origins:
#    - http://127.0.0.1:5173
#    - http://localhost:5173
#    - http://localhost:3000
  auth:
    ldap:
      enabled: false
#      url: "ldap://127.0.0.1:389/dc=home,dc=lab"
#      userDnPatterns:
#        - "uid={0}"
#        - "cn={0},ou=users"
#      userSearchFilter: "(cn={0})"
    proxy:
      enabled: false
      adminName: "adminproxy"
  lucene:
    indexAnalyzer:
      minGram: 3

server:
  port: 11111
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:liquibase.xml
  datasource:
    url: jdbc:sqlite:${jelu.database.path}/jelu.db?foreign_keys=on;
    username: jelu_user
    password: mypass1234
    driver-class-name: org.sqlite.JDBC
  exposed:
    generate-ddl: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      max-request-size: 10MB
      max-file-size: 10MB
logging:
  logback.rollingpolicy.max-history: 10
  file:
    name: ${jelu.database.path}/jelu.log
    #    name: \${user.home}/.jelu/jelu.log
  level:
    io.github.bayang.jelu: DEBUG
    io.github.bayang.jelu.service.metadata: TRACE
    io.github.bayang.jelu.service.quotes: DEBUG
    io.github.bayang.jelu.service.FileManager: TRACE
    io.github.bayang.jelu.config.JeluLdapUserDetailsContextMapper: TRACE
    org.springframework.security.ldap: TRACE
